spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: Leavezhongway!
    url: jdbc:mysql://localhost:3306/sell?useUnicode=true&characterEncoding=utf-8&useSSL=false&serverTimezone=GMT%2B8
  jpa:
    show-sql: true

server:
  servlet:
    context-path: /sell
  port: 9001
